[parity]
chain = "proof-of-authority-spec.json"
base_path = "/opt/poa-data/parity1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8181
[dapps]
port = 8081
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00523A4e2Ee1894228D287bC9bfF9892D02dff99"
reseal_on_txs = "none"