[parity]
chain = "proof-of-authority-spec.json"
base_path = "/opt/poa-data/parity3"
[network]
port = 30303
[rpc]
port = 8543
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8183
[dapps]
port = 8083
