[parity]
chain = "proof-of-authority-spec.json"
base_path = "/opt/poa-data/parity4"
[network]
port = 30304
[rpc]
port = 8544
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8184
[dapps]
port = 8084
