[parity]
chain = "proof-of-authority-spec.json"
base_path = "/opt/poa-data/parity5"
[network]
port = 30305
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8185
[dapps]
port = 8085
